language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
jdk:
  - oraclejdk7
  - openjdk7
gemfile:
  - travis/ar32.gemfile
  - travis/ar40.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: jruby-18mode
      gemfile: travis/ar40.gemfile
      jdk: openjdk7
    - rvm: jruby-18mode
      gemfile: travis/ar40.gemfile
      jdk: oraclejdk7
# TEMP: jdbc adapters don't seem to work with Rails 4 yet, as of 2013-02-27
    - rvm: jruby-19mode
      gemfile: travis/ar40.gemfile
      jdk: openjdk7
    - rvm: jruby-19mode
      gemfile: travis/ar40.gemfile
      jdk: oraclejdk7
# END TEMP
before_install:
  - sudo apt-get update
  - sudo apt-get install libproj-dev libgeos-dev libffi-dev
script: bundle exec rake spec